export const content = {
  eyebrowEn: 'A private collection, officially archived',
  eyebrowNe: 'एउटा निजी संग्रह, विधिवत् अभिलेखित',
  titleEn: 'Our little archive',
  titleNe: 'हाम्रो सानो संग्रह',
  introEn: 'A home for the tiny apps, grand gestures, and beautifully unnecessary digital paperwork made for us.',
  introNe: 'हाम्रा लागि बनाइएका साना एपहरू, ठूला भावनाहरू र सुन्दर रूपमा अनावश्यक डिजिटल कागजपत्रहरूको घर।',
  collectionLabelEn: 'Filed chapters',
  collectionLabelNe: 'दर्ता भएका अध्यायहरू',
  entries: [{
    number: '001',
    statusEn: 'Available now',
    statusNe: 'अहिले उपलब्ध',
    titleEn: 'Official Gallery Access Request',
    titleNe: 'आधिकारिक ग्यालरी पहुँच निवेदन',
    summaryEn: 'A respectfully dramatic petition concerning one masterpiece and its rightful place in a gallery.',
    summaryNe: 'एउटा उत्कृष्ट तस्वीर र ग्यालरीमा त्यसको उचित स्थानबारे सम्मानपूर्वक नाटकीय निवेदन।',
    href: '/apps/niwedan/',
    ctaEn: 'Open the filing',
    ctaNe: 'निवेदन खोल्नुहोस्',
  }, {
    number: '002',
    statusEn: 'A little rest stop',
    statusNe: 'सानो विश्रामस्थल',
    titleEn: 'Flowers for Today',
    titleNe: 'आजका लागि फूलहरू',
    summaryEn: 'A quiet evening meadow where every tap grows a small thank-you for a very full day.',
    summaryNe: 'धेरै व्यस्त दिनका लागि, हरेक स्पर्शले सानो धन्यवादको फूल फुलाउने शान्त साँझको मैदान।',
    href: '/apps/flower-field/',
    ctaEn: 'Walk through the field',
    ctaNe: 'फूलबारीमा हिँड्नुहोस्',
  }, {
    number: '003',
    statusEn: 'Available now',
    statusNe: 'अहिले उपलब्ध',
    availableStatusEn: 'Available now',
    availableStatusNe: 'अहिले उपलब्ध',
    titleEn: 'Mission 143',
    titleNe: 'मिसन १४३',
    summaryEn: 'A small after-hours robot mission with questions, tiny lives, and a very particular soundtrack.',
    summaryNe: 'प्रश्नहरू, साना जीवनहरू र विशेष धुन भएको रातपछिको रोबोट मिसन।',
    href: '/apps/mission-143/',
    ctaEn: 'Enter the lab',
    ctaNe: 'प्रयोगशाला खोल्नुहोस्',
  }],
  futureTitleEn: 'More chapters will appear here.',
  futureTitleNe: 'यहाँ अझै धेरै अध्यायहरू थपिनेछन्।',
  footerEn: 'Made slowly, kept carefully.',
  footerNe: 'बिस्तारै बनाइएको, जतनले राखिएको।',
}
