import { useEffect, useReducer, useRef, useState } from 'react'
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'
import { gameContent as content, withNames, applyUnlock, unlockedMedia } from './data/gameContent.js'
import { advanceResolved, advanceWakeRhythm, answerGame, initialGame, playAgain, refreshReplayTransition, resetWakeRhythm, restartAfterGameover, stepBack } from './gameEngine.js'

const KEY = 'mission-143:campaign'; const SESSION = 'mission-143:session'; const bootId = globalThis.crypto?.randomUUID?.() || String(Date.now()); const copy = content.copy
const fill = value => withNames(String(value || ''))
const read = (storage, key, fallback) => { try { return JSON.parse(storage.getItem(key)) || fallback } catch { return fallback } }
const save = (storage, key, value) => { try { storage.setItem(key, JSON.stringify(value)) } catch {} }

function ParticleField({ active }) { const canvas = useRef(null); const reduced = useReducedMotion(); useEffect(() => { const el = canvas.current; if (!el || !active || reduced) return; const ctx = el.getContext('2d'); let frame; const dots = Array.from({ length: 42 }, () => ({ x: Math.random(), y: Math.random(), r: 1 + Math.random() * 2, v: .002 + Math.random() * .004, a: Math.random() * Math.PI * 2, av: (Math.random() - .5) * .012 })); const heart = size => { ctx.beginPath(); ctx.moveTo(0, size * .32); ctx.bezierCurveTo(size * .5, -size * .4, size * 1.2, size * .32, 0, size * 1.15); ctx.bezierCurveTo(-size * 1.2, size * .32, -size * .5, -size * .4, 0, size * .32); ctx.fill() }; const paint = () => { const box = el.getBoundingClientRect(); el.width = box.width * devicePixelRatio; el.height = box.height * devicePixelRatio; ctx.setTransform(devicePixelRatio, 0, 0, devicePixelRatio, 0, 0); ctx.clearRect(0, 0, box.width, box.height); ctx.fillStyle = '#F2A0B8'; dots.forEach(dot => { dot.y -= dot.v; dot.a += dot.av; if (dot.y < 0) dot.y = 1; ctx.globalAlpha = Math.min(.45, .15 + dot.y * .45); ctx.save(); ctx.translate(dot.x * box.width, dot.y * box.height); ctx.rotate(dot.a); heart(dot.r * 2); ctx.restore() }); frame = requestAnimationFrame(paint) }; paint(); return () => cancelAnimationFrame(frame) }, [active, reduced]); return <canvas className="particles" ref={canvas} aria-hidden="true"/> }
function Robot({ mood = 'sleep', onTap, taps = [] }) { const art = <><span className="robot-shadow"/><span className="antenna"><i className="heart"/></span><span className="head"><i className="ear left"/><i className="ear right"/><span className="face"><b className="brow left"/><b className="brow right"/><b className="eye left"><u/></b><b className="eye right"><u/></b><b className="mouth"/></span><i className="cheek left"/><i className="cheek right"/></span><span className="torso"><i className="core heart"/></span><span className="arm left"/><span className="arm right"/><span className="leg left"/><span className="leg right"/><span className="zzz" aria-hidden="true"><i/><i/><i/></span></>; return onTap ? <button className={`robot ${mood}`} type="button" onClick={onTap} aria-label={`${copy.wakeTitle} ${taps.join(' ')}`}>{art}</button> : <div className={`robot ${mood}`} aria-hidden="true">{art}</div> }
function useAudio() { const bg = useRef(null); const reveal = useRef(null); const [enabled, setEnabled] = useState(false); const [notice, setNotice] = useState(''); const [blocked, setBlocked] = useState(false); useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 5000); return () => clearTimeout(timer) }, [notice]); const setMusic = async value => { setBlocked(false); if (!value) { setEnabled(false); return bg.current?.pause() } try { await bg.current?.play(); setEnabled(true) } catch (error) { setEnabled(false); if (error?.name === 'NotAllowedError') setBlocked(true); else setNotice(copy.audioMissing) } }; const playReveal = async () => { const resume = enabled; bg.current?.pause(); const el = reveal.current; if (!el) { if (resume) bg.current?.play().catch(() => {}); return } const finish = () => { el.pause(); el.removeEventListener('timeupdate', onTime); el.removeEventListener('ended', finish); if (resume) bg.current?.play().catch(() => {}) }; const onTime = () => { if (el.currentTime >= content.audio.revealEnd) finish() }; el.addEventListener('timeupdate', onTime); el.addEventListener('ended', finish); try { el.currentTime = content.audio.revealStart; await el.play(); if (el.currentTime < content.audio.revealStart) el.currentTime = content.audio.revealStart } catch { el.removeEventListener('timeupdate', onTime); el.removeEventListener('ended', finish); setNotice(copy.audioMissing); if (resume) bg.current?.play().catch(() => {}) } }; return { bg, reveal, enabled, setMusic, playReveal, notice, blocked } }

export default function App() {
  const reduced = useReducedMotion(); const sessionRef = useRef(read(sessionStorage, SESSION, {}))
  // Reapply a persisted unlock (names/media/aliases) before any screen that needs it
  // renders, so a mid-game refresh does not fall back to the neutral placeholders.
  applyUnlock(sessionRef.current.unlock)
  const refreshChecked = useRef(false); const sceneRef = useRef(null)
  const [stage, setStage] = useState(() => sessionRef.current.stage || 'gate'); const [personName, setPersonName] = useState(() => sessionRef.current.personName || ''); const [sharing, setSharing] = useState(() => sessionRef.current.sharing ?? null); const [musicChoice, setMusicChoice] = useState(() => sessionRef.current.musicChoice ?? null)
  const [identity, setIdentity] = useState(''); const [identityError, setIdentityError] = useState(''); const [identityPending, setIdentityPending] = useState(false); const [readyNote, setReadyNote] = useState(''); const [answer, setAnswer] = useState(''); const [rhythm, setRhythm] = useState([]); const [shareError, setShareError] = useState('')
  const rhythmRef = useRef(resetWakeRhythm()); const resetTimer = useRef()
  const [game, dispatch] = useReducer((state, action) => action.game || state, null, () => read(localStorage, KEY, initialGame()))
  const audio = useAudio(); const question = content.questions[game.index]
  useEffect(() => { const next = { ...sessionRef.current, stage, personName, sharing, musicChoice }; sessionRef.current = next; save(sessionStorage, SESSION, next) }, [stage, personName, sharing, musicChoice])
  useEffect(() => { save(localStorage, KEY, game) }, [game])
  useEffect(() => { if (refreshChecked.current) return; refreshChecked.current = true; const prior = read(localStorage, KEY, null); const next = refreshReplayTransition(prior, bootId); if (next && next !== prior) dispatch({ game: next }) }, [])
  useEffect(() => { if (sceneRef.current) sceneRef.current.scrollTop = 0 }, [stage, game.index, game.status])
  useEffect(() => { if (musicChoice && stage === 'quiz' && !audio.enabled) audio.setMusic(true) }, [stage, musicChoice])
  useEffect(() => () => clearTimeout(resetTimer.current), [])
  const sendEvent = async (event, result, rawAnswer = '') => { if (!sharing) return; const stableSession = sessionRef.current.sessionId; const payload = { version: 1, eventId: crypto.randomUUID(), sessionId: stableSession, event, questionId: question?.id || 'mission', runNumber: result.last?.runNumber || result.runNumber, attemptNumber: result.last?.attemptNumber || 0, answer: String(rawAnswer).slice(0, 160), correct: Boolean(result.last?.correct), lifeLost: Boolean(result.last?.lifeLost), livesRemaining: result.lives, streak: result.streak, replayCount: result.replayCount }; try { const response = await fetch('/api/quiz-event', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) throw Error() } catch { setShareError(copy.sharingUnavailable); setSharing(false) } }
  const tapRobot = () => { const next = advanceWakeRhythm(rhythmRef.current, Date.now(), content.wake); rhythmRef.current = next; setRhythm(next.groups); clearTimeout(resetTimer.current); if (next.matched) { rhythmRef.current = resetWakeRhythm(); setRhythm([]); setStage('identity'); return } resetTimer.current = setTimeout(() => { rhythmRef.current = resetWakeRhythm(); setRhythm([]) }, content.wake.resetAfter) }
  const confirmIdentity = async event => { event.preventDefault(); setIdentityPending(true); try { const response = await fetch('/api/mission-unlock', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ version: 1, name: identity }) }); if (response.status === 200) { const payload = await response.json(); applyUnlock(payload); sessionRef.current = { ...sessionRef.current, unlock: payload }; save(sessionStorage, SESSION, sessionRef.current); setPersonName(identity.trim()); setIdentityError(''); setStage('rules') } else if (response.status === 401) { setIdentityError(copy.identityWrong) } else { setIdentityError(copy.identityUnavailable) } } catch { setIdentityError(copy.identityUnavailable) } finally { setIdentityPending(false) } }
  const chooseMusic = value => { setMusicChoice(value); audio.setMusic(value); setStage('wake') }
  const toggleMusic = () => { const next = !audio.enabled; setMusicChoice(next); audio.setMusic(next) }
  const startQuiz = choice => { const sessionId = sessionRef.current.sessionId || crypto.randomUUID(); sessionRef.current = { ...sessionRef.current, sessionId, stage: 'quiz', personName, sharing: choice }; save(sessionStorage, SESSION, sessionRef.current); setSharing(choice); setStage('quiz'); dispatch({ game: { ...initialGame(0, true), bootId } }) }
  const submitAnswer = async value => { if (value === '' || value == null || !question) return; const result = answerGame(game, question, value); dispatch({ game: result }); setAnswer(''); const raw = question.type.startsWith('text') ? value : fill(question.options[value]); await sendEvent('answer_attempt', result, raw); if (result.status === 'gameover') await sendEvent('run_failed', result, raw); if (question.audioReveal && result.status === 'resolved') audio.playReveal() }
  const continueResolved = async () => { const next = advanceResolved(game, content.questions.length); dispatch({ game: next }); if (next.status === 'complete') await sendEvent('run_completed', next) }
  const goBack = () => dispatch({ game: stepBack(game, content.questions[game.index - 1]?.id) })
  const beginAgain = () => { const next = game.status === 'gameover' ? restartAfterGameover(game) : playAgain(); dispatch({ game: { ...next, bootId } }); setStage('quiz') }
  const scene = () => {
    if (stage === 'gate') return <Screen><Robot mood="sleep"/><p className="eyebrow">{copy.available}</p><h1>{copy.enter}</h1><p>{copy.musicBody}</p><div className="actions"><button className="primary" onClick={() => chooseMusic(true)}>{copy.withMusic}</button><button onClick={() => chooseMusic(false)}>{copy.withoutMusic}</button></div></Screen>
    if (stage === 'wake') return <Screen><Robot mood="sleep" onTap={tapRobot} taps={rhythm}/><p className="eyebrow">{copy.wakeProgress}: {rhythm.join(' · ') || copy.wakeEmpty}</p><h1>{copy.wakeTitle}</h1><p>{copy.wakeBody}</p><p className="robot-line">{copy.robot.sleep}</p></Screen>
    if (stage === 'identity') return <Screen><Robot mood="wake"/><p className="eyebrow">{copy.robot.wake}</p><h1>{copy.identityTitle}</h1><p>{fill(copy.identityBody)}</p><form onSubmit={confirmIdentity}><label>{copy.identityLabel}<input autoFocus value={identity} onChange={event => setIdentity(event.target.value)}/></label><button className="primary" disabled={identityPending}>{identityPending ? copy.identityPending : copy.identityButton}</button></form>{identityError && <p className="feedback bad" role="alert">{identityError}</p>}</Screen>
    if (stage === 'rules') return <Screen><Robot mood="shock"/><p className="eyebrow">{fill(copy.robot.shock.replace('{name}', personName || content.people.s.name))}</p><h1>{copy.rulesTitle}</h1><p>{copy.identityHello}</p><ul>{copy.rules.map(item => <li key={item}>{item}</li>)}</ul><div className="actions equal"><button className="primary" onClick={() => setStage('consent')}>{copy.ready}</button><button onClick={() => setReadyNote(copy.notReadyReply)}>{copy.notReady}</button></div>{readyNote && <p className="feedback">{readyNote}</p>}</Screen>
    if (stage === 'consent') return <Screen><Robot mood="happy"/><h1>{copy.consentTitle}</h1><p>{fill(copy.consentBody)}</p><div className="actions equal"><button className="primary" onClick={() => startQuiz(true)}>{copy.share}</button><button onClick={() => startQuiz(false)}>{copy.private}</button></div></Screen>
    if (game.status === 'gameover') return <Screen><Robot mood="gameover"/><h1>{copy.gameOverTitle}</h1><p>{copy.gameOverBody}</p><button className="primary" onClick={beginAgain}>{copy.restart}</button></Screen>
    if (game.status === 'complete') return <Results game={game} onRestart={beginAgain}/>
    return <Question question={question} game={game} answer={answer} setAnswer={setAnswer} onAnswer={submitAnswer} onContinue={continueResolved} onBack={goBack}/>
  }
  return <main className="mission"><audio ref={audio.bg} src={content.audio.background} loop preload="none"/><audio ref={audio.reveal} src={content.audio.reveal} preload="metadata"/><ParticleField active={stage === 'wake' || game.status === 'complete'}/><header><a href="/" className="back">← Archive</a><p className="brand">{content.title}</p>{stage !== 'gate' && <button className="audio-toggle" onClick={toggleMusic}>{audio.enabled ? copy.mute : copy.unmute}</button>}</header><section className="scene" ref={sceneRef} aria-live="polite"><AnimatePresence mode="wait"><motion.div key={`${stage}-${game.index}-${game.status}`} initial={reduced ? false : { opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} exit={reduced ? {} : { opacity: 0, y: -12 }} transition={{ duration: .35 }}>{scene()}</motion.div></AnimatePresence></section>{stage === 'quiz' && ['playing', 'resolved'].includes(game.status) && <footer><p>{copy.lives}: {game.lives}. {copy.streak}: {game.streak}.</p>{sharing && <button onClick={() => setSharing(false)}>{copy.stopSharing}</button>}{shareError && <p role="status">{shareError}</p>}</footer>}{audio.blocked && <p className="audio-notice" role="status">{copy.audioResume} <button onClick={() => audio.setMusic(true)}>{copy.resumeMusic}</button></p>}{audio.notice && <p className="audio-notice" role="status">{audio.notice}</p>}</main>
}
function Screen({ children, className = '' }) { return <article className={`screen ${className}`}>{children}</article> }
function TypingLine() { const reduced = useReducedMotion(); return <p className={`typing ${reduced ? 'instant' : ''}`}><span aria-hidden="true">{copy.typingLine}</span><span className="sr-only">{copy.typingLine}</span></p> }
function Question({ question, game, answer, setAnswer, onAnswer, onContinue, onBack }) {
  const attempts = game.history.filter(item => item.questionId === question.id && item.runNumber === game.runNumber); const last = game.last?.questionId === question.id ? game.last : null; const resolved = game.status === 'resolved'; const text = question.type.startsWith('text'); const response = last && (last.correct ? question.feedback || copy.correct : question.type === 'trap' ? (last.trapComplete ? question.feedback : copy.wrong) : resolved ? `${copy.reveal}: ${fill(question.reveal || question.options?.[question.answer] || '')}` : last.lifeLost ? copy.wrong : copy.retry)
  return <Screen className={`quiz${question.media ? ' wide' : ''}`}><p className="eyebrow">{copy.questionOf.replace('{current}', game.index + 1).replace('{total}', content.questions.length)}</p><Robot mood={last?.correct ? 'happy' : last ? 'disappointed' : 'wake'}/><h1>{fill(question.prompt)}</h1>{question.id === 'nickname' && <TypingLine/>}<p className="attempt-note">{question.type === 'text3' ? `${copy.attempts}: ${attempts.length} / 3` : ''}</p>{text ? <form onSubmit={event => { event.preventDefault(); onAnswer(answer) }}><label>{fill(question.label || copy.answer)}<input autoFocus disabled={resolved} value={answer} onChange={event => setAnswer(event.target.value)} placeholder={copy.typedHint}/></label><button className="primary" disabled={resolved}>{copy.submit}</button></form> : <div className={`options${question.media ? ` media media-${question.media}` : ''}`}>{question.options.map((option, index) => <button key={option} disabled={resolved || (question.type === 'trap' && game.trapSeen.includes(index))} onClick={() => onAnswer(index)}>{question.media && <OptionMedia item={unlockedMedia(question.media)[index]}/>}<span>{fill(option)}</span></button>)}</div>}{response && <p className={`feedback ${last?.correct ? 'good' : 'bad'}`}>{fill(response)}</p>}{resolved && <button className="primary continue" onClick={onContinue}>{copy.continue}</button>}{game.index > 0 && <button className="step-back" onClick={onBack}>← {copy.back}</button>}</Screen>
}
// Video is always muted: autoplay is blocked without it, and the background song
// is already playing. No controls, and pointer-events are off in CSS, so a tap
// anywhere on the card still selects that option rather than scrubbing the clip.
function OptionMedia({ item }) { const reduced = useReducedMotion(); if (!item.src) return <span className="option-media placeholder" role="img" aria-label={fill(item.alt) || copy.placeholderImage}>{fill(item.alt) || copy.placeholderImage}</span>; return item.type === 'video' ? <video className="option-media" src={item.src} muted playsInline loop autoPlay={!reduced} preload="metadata" aria-label={fill(item.alt)} role="img"/> : <img className="option-media" src={item.src} alt={fill(item.alt)} loading="lazy"/> }
function Results({ game, onRestart }) { const records = content.questions.map(question => ({ question, attempts: game.history.filter(item => item.questionId === question.id) })).filter(item => item.attempts.length); return <Screen><Robot mood="celebrate"/><p className="eyebrow">{copy.completed}</p><h1>{copy.resultsTitle}</h1><p>{copy.resultsBody}</p><dl className="stats"><div><dt>{copy.lives}</dt><dd>{game.lives}</dd></div><div><dt>{copy.attempts}</dt><dd>{game.attempts}</dd></div><div><dt>{copy.firstTry}</dt><dd>{game.firstTry}</dd></div><div><dt>{copy.livesLost}</dt><dd>{game.livesLost}</dd></div><div><dt>{copy.bonusLives}</dt><dd>{game.bonusLives}</dd></div><div><dt>{copy.replays}</dt><dd>{game.replayCount}</dd></div></dl><h2>{copy.preference}</h2><ul className="history">{Object.entries(game.preferences).map(([id, answer]) => { const question = content.questions.find(item => item.id === id); const prompt = fill(question.prompt).replace(/[:\s]+$/, ''); const separator = /[?!.]$/.test(prompt) ? ' ' : ': '; return <li key={id}>{prompt}{separator}{fill(question.options[answer])}</li> })}</ul><h2>{copy.attemptSummary}</h2><ul className="history">{records.map(({ question, attempts }) => <li key={question.id}><b>{fill(question.prompt)}</b><br/>{attempts.length} {(attempts.length === 1 ? copy.attempt : copy.attempts).toLowerCase()}. {attempts.some(item => item.correct) ? copy.success : copy.reveal}. {attempts.some(item => item.lifeLost) ? copy.lostLife : copy.noLifeLost}.</li>)}</ul><button className="primary" onClick={onRestart}>{copy.playAgain}</button></Screen> }
