export const storyIntro = {
  kickerEn: 'A little record of a very big effort',
  kickerNe: 'ठूलो मेहनतको सानो अभिलेख',
  titleEn: 'You did it.',
  titleNe: 'तिमीले गर्‍यौ।',
  leadEn: 'A Finance degree, built one ordinary, determined day at a time.',
  leadNe: 'एक-एक दिनको अठोटले बनेको Finance को degree।',
  scrollEn: 'Scroll to follow your journey',
  scrollNe: 'तिम्रो यात्रा हेर्न तल जाऊ',
}

export const storyScenes = [
  {
    id: 'campus', number: '01', eyebrowEn: 'Shankar Dev · Baghbazar', eyebrowNe: 'शंकरदेव · बागबजार',
    titleEn: 'You kept showing up.', titleNe: 'तिमी अघि बढिरह्यौ।',
    bodyEn: 'Classes, work, another semester. You made room for all of it and kept going.',
    bodyNe: 'कक्षा, काम, अनि अर्को semester। सबैका लागि समय निकालेर तिमी अघि बढिरह्यौ।',
    noteEn: 'Main task: pass the semester. Background characters: please keep your distance.',
    noteNe: 'मुख्य काम: semester पार गर्ने। पृष्ठभूमिका पात्र: टाढै रहनुहोला।',
    sceneLabel: 'Illustrated Shankar Dev campus at dusk, with her walking along a lit path.',
  },
  {
    id: 'office', number: '02', eyebrowEn: 'Work + final exams', eyebrowNe: 'काम + अन्तिम परीक्षा',
    titleEn: 'A full-time job. A finish line in sight.', titleNe: 'full-time काम। अन्तिम चरण नजिक।',
    bodyEn: 'You worked through college. By the time your final exams ended, you were already working full time.',
    bodyNe: 'कलेजसँगै तिमीले काम गर्यौ। अन्तिम परीक्षा सकिँदा तिमी full-time काम गरिरहेकी थियौ।',
    noteEn: 'The office light stayed on. So did your determination.',
    noteNe: 'office को बत्ती बलिरह्यो। तिम्रो अठोट पनि।',
    sceneLabel: 'An office at evening with a desk, lamp, work papers and exam books.',
  },
  {
    id: 'online', number: '03', eyebrowEn: 'A small hello', eyebrowNe: 'एउटा सानो hello',
    titleEn: 'A hello from far away.', titleNe: 'टाढाबाट एउटा hello।',
    bodyEn: 'We met online as your final exams were ending, just before the 2026 World Cup. I was outside Nepal; your college journey was already yours.',
    bodyNe: 'तिम्रो अन्तिम परीक्षा सकिँदै गर्दा, २०२६ World Cup अघि, हाम्रो online भेट भयो। म नेपालबाहिर थिएँ; कलेजको यात्रा पहिल्यै तिम्रै थियो।',
    noteEn: 'A little connection in your much bigger story.',
    noteNe: 'तिम्रो ठूलो कथामा एउटा सानो सम्बन्ध।',
    sceneLabel: 'A quiet evening skyline and a small message crossing a distance.',
  },
  {
    id: 'thesis', number: '04', eyebrowEn: 'The thesis', eyebrowNe: 'thesis',
    titleEn: 'Your words, your work, your PDF.', titleNe: 'तिम्रै लेखाइ, तिम्रै मेहनत, तिम्रै PDF।',
    bodyEn: 'You wrote the thesis yourself. Then, out of the blue, you sent me the PDF for AI-assisted structure cleanup only. You handled the supervisor’s tiny corrections too.',
    bodyNe: 'thesis तिमीले आफैँ लेख्यौ। अनि एक्कासि PDF पठाएर AI बाट structure मिलाउन मात्रै भन्यौ। supervisor का ससाना correction पनि तिमीले नै मिलायौ।',
    noteEn: 'A neat layout is nice. The research was the real mountain.',
    noteNe: 'मिलेको layout राम्रो हो। असली पहाड research नै थियो।',
    sceneLabel: 'Her thesis pages, a marked PDF and small supervisor corrections.',
  },
  {
    id: 'tea', number: '05', eyebrowEn: 'Submission day', eyebrowNe: 'submission को दिन',
    titleEn: 'Submitted. Exhale. Tea.', titleNe: 'बुझाइयो। सास फेरियो। चिया।',
    bodyEn: 'After you submitted the thesis, we had tea outside campus. A small pause for work you had carried all the way through.',
    bodyNe: 'तिमीले thesis बुझाएपछि हामीले क्याम्पसबाहिर चिया पियौँ। अन्त्यसम्म पुर्‍याएको तिम्रो मेहनतका लागि सानो विश्राम।',
    noteEn: 'You had more than earned that cup.',
    noteNe: 'त्यो चिया तिमीले साँच्चै कमाएकी थियौ।',
    sceneLabel: 'Two cups of tea at a stall outside campus after thesis submission.',
  },
  {
    id: 'result', number: '06', eyebrowEn: 'The good news', eyebrowNe: 'राम्रो खबर',
    titleEn: 'Every subject passed. Finance bachelor complete.', titleNe: 'सबै subject पास। Finance bachelor पूरा।',
    bodyEn: 'The result is here. Every subject passed. All that work, every exam and every revision led to this moment. You did it.',
    bodyNe: 'नतिजा आयो। सबै subject पास। तिम्रो काम, परीक्षा र हरेक सुधारले यही पलसम्म पुर्‍यायो। तिमीले गर्यौ।',
    noteEn: 'Officially, wonderfully proud of you.',
    noteNe: 'आधिकारिक रूपमा, तिमीमाथि धेरै गर्व छ।',
    sceneLabel: 'She celebrates beneath golden paper confetti, holding the good result.',
  },
]
